project_id = "ohwaygqxelyaytljbcsb"

[functions.kiwify-products]
verify_jwt = false

[functions.hotmart-products]
verify_jwt = false

[functions.guru-products]
verify_jwt = false

[functions.eduzz-products]
verify_jwt = false

[functions.meta-campaigns]
verify_jwt = false

[functions.sync-project-data]
verify_jwt = false

[functions.sync-public-project]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.generate-daily-report]
verify_jwt = false

[functions.create-embedded-checkout]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-email-change]
verify_jwt = false

[functions.admin-projects]
verify_jwt = false
